ProjectRestaurant/ProjectRestaurant/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.CodeAnalysis.Differencing;
using ProjectRestaurant.Data.Entities;
using ProjectRestaurant.Hubs;
using ProjectRestaurant.Models;
using ProjectRestaurant.Service.Dto;
using ProjectRestaurant.Service.Service;

namespace ProjectRestaurant.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly RestaurantService _restaurantService;
        private readonly TableService _tableService;
        private readonly IMapper _mapper;
        public RestaurantController(RestaurantService restaurantService, TableService tableService, IMapper mapper)
        {
            _restaurantService = restaurantService;
            _tableService = tableService;
            _mapper = mapper;
        }
        [Authorize]
        public IActionResult Index()
        {
            var tables = _tableService.GetAllTables();
            var mapped = _mapper.Map<List<TableViewModel>>(tables);
            return View(mapped);
        }
        public IActionResult NewRestaurant()
        {
            var result= _tableService.GetAllTables();
            return View();
        }
        
        [HttpPost]
        public  async  Task<IActionResult> NewRestaurant(NewRestaurantSignUpViewModel model)
        {
            var mapped = _mapper.Map<NewRestaurantDto>(model);
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await _restaurantService.NewRestaurant(mapped);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(LoginRestaurant));
            }
            return View();
        }
       
        public IActionResult LoginRestaurant()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> LoginRestaurant(RestaurantSignInViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var mapped = _mapper.Map<RestoranLoginDto>(model);
            
            var result = await _restaurantService.Login(mapped);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        [Authorize]
        public IActionResult Logout()
        {
            _restaurantService.Logout();
            return RedirectToAction(nameof(LoginRestaurant));
        }
        [Authorize]
        public async Task<IActionResult> EditRestaurant()
        {
            var rest = await _restaurantService.GetRestaurantInfo(User.Identity.Name);
            var mapped = _mapper.Map<RestaurantEditViewModel>(rest);
            return View(mapped);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditRestaurant(RestaurantEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var mapped = _mapper.Map<Restaurant>(model);
            var result= await _restaurantService.UpdateRestaurantInfo(mapped);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }
        [Authorize]
        public IActionResult NewTable()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public  async Task<IActionResult> NewTable(NewTableViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var mapped = _mapper.Map<Table>(model);
            await _tableService.AddNewTable(mapped,User.Identity.Name);
            return RedirectToAction(nameof(Tables));
        }
        [Authorize]
        public async Task<IActionResult> DeleteTable(int id)
        {
            await _tableService.DeleteTable(id);
            return RedirectToAction(nameof(Tables));
        }
        [Authorize]
        public IActionResult EditTable(int id)
        {
            var table = _tableService.GetTableById(id);
            var mapped = _mapper.Map<EditTableViewModel>(table);
            return View(mapped);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditTable(EditTableViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var mapped = _mapper.Map<Table>(model);
            var result =await _tableService.EditTable(mapped);
            if (result > 0)
            {
                return RedirectToAction(nameof(Tables));
            }
            return View(model);
        }
        [Authorize]
        public IActionResult Tables()
        {
            var tables = _tableService.GetAllTables();
            var mapped = _mapper.Map<List<TableViewModel>>(tables);

            return View(mapped);
        }
        
        [Authorize]
        public IActionResult TableDetail(int id)
        {
            
            var session = _restaurantService.GetSessionDetail(id);
            var mapped = _mapper.Map<SessionViewModel>(session);
            return View(mapped);
        }
        [Authorize]
        public IActionResult DeliverOrder(int id)
        {
            _restaurantService.DeliverOrder( id);
            return RedirectToAction(nameof(Index));
        }
        [Authorize]
        public IActionResult CloseSession(int id)
        {
            _restaurantService.CloseSession(id);
            return Ok();
        }
        public IActionResult CancelOrders(int id)
        {
            var session = _restaurantService.GetSessionDetail(id);
            var mapped = _mapper.Map<SessionViewModel>(session);
            return View(mapped);
        }
    }
}

ProjectRestaurant/ProjectRestaurant/Views/Restaurant/CancelOrders.cshtml
@model SessionViewModel
@{
    ViewData["Title"] = "Sipariş İptali";
}
<style>
    body {
        background-image: url('/image/cafebackground.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
    .col-md-4 a {
        background-color: rgba(2, 147, 0, 0);
        color: rgb(255, 255, 255);
        border-color: rgb(255, 255, 255);
    }

    .col-md-4 > button {
        background-color: rgba(2, 147, 0, 0);
        color: rgb(255, 255, 255);
        border-color: rgb(255, 255, 255);
    }

    .more {
        display: none
    }

    .col-md-4 a:hover {
        background-color: #ee7500;
        border-color: rgb(255, 255, 255);
        color: rgb(255, 255, 255);
    }

    .col-md-4 button:hover {
        background-color: #ee7500;
        border-color: rgb(255, 255, 255);
        color: rgb(255, 255, 255);
    }

    #grid {
        display: grid;
        grid-template-columns: 20% 20% 20% 20% 20%;
        padding-left: 10px;
        padding-right: 10px;
    }

        #grid div {
            text-align: center;
            vertical-align: middle;
            padding-bottom: 25px;
            padding-top: 25px;
            margin-top: auto;
            margin-bottom: auto;
        }

        #grid .row {
            margin-left: auto;
            margin-right: auto;
        }

    #quantityBox {
        resize: none;
        width: 50px;
        height: 40px;
        white-space: normal;
        text-align: justify;
        -moz-text-align-last: center;
        text-align-last: center;
    }
    .tableId {
        background-color: rgba(0, 0, 0, 0.8);
        border-radius: 25px 25px 20px 25px;
        padding: 10px 10px 10px 10px;
    }

    .modal-content {
        background-color: rgba(0, 0, 0, 1);
        color: white;
        text-align: center;
    }

    #modalTitle {
        margin: auto;
        font-style: italic;
        color: white;
        font-size: 30px;
    }
</style>
    <div class="container tableId">
        <div><h2>@Model.TableName</h2></div>
        <div class="row">
            <div class="col-md-8">
                <table class="table table-dark table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Sipariş No</th>
                            <th>Ürün</th>
                            <th>Adet</th>                            
                            <th>Çıkar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Order.Count; i++)
                        {
                            if (Model.Order[i].isDelivered)
                            {
                        <tr>
                            <td>  @Model.Order[i].OrderId</td>
                            <td>@Model.Order[i].ProductName</td>
                            <td>
                                <div class="row">
                                    <button id="subQuantity" class="btn btn-outline-danger">-</button>
                                    <textarea disabled="disabled" id="quantityBox" class="form-control  @Model.Order[i].Quantity" rows="1" maxlength="2">@Model.Order[i].Quantity</textarea>
                                    <button id="addQuantity" class="btn btn-outline-success">+</button>
                                </div>
                            </td>
                            <td><div><button id="Sub" class="btn btn-outline-primary">-</button></div></td>

                        </tr>
                            }
                            else
                            {
                    <tr class="table-secondary" style="color:#000000">
                        <td>  @Model.Order[i].OrderId</td>
                        <td>@Model.Order[i].ProductName</td>
                        <td>
                            <div class="row">
                                <button id="subQuantity" class="btn btn-outline-danger">-</button>
                                <textarea disabled="disabled" id="quantityBox" class="form-control @Model.Order[i].Quantity" rows="1" maxlength="2">@Model.Order[i].Quantity</textarea>
                                <button id="addQuantity" class="btn btn-outline-success">+</button>
                            </div>
                        </td>
                        <td><div><button id="Sub" class="btn btn-outline-primary">-</button></div></td>
                        <td> @Html.HiddenFor(x => Model.Order[i].OrderId)</td>
                    </tr>
                               
                            }

                        }

                    </tbody>
                </table>
            </div>
            <div class="col-md-4">
                <table class="table table-dark table-striped table-hover">
                    <thead>
                        <tr><th>Sipariş No</th>
                            <th scope="col">Ürün</th>
                            <th scope="col">Adet</th>                            
                            <th scope="col">Çıkar</th>
                        </tr>
                    </thead>
                    <tbody id="sepet">
                    </tbody>
                </table>
                <div style="text-align:center">
                    <button class="btn btn-outline-light" id="iptal"> İptal</button>
                </div>
            </div>
        </div>
    </div>
<script>
    document.body.addEventListener("click", function (event) {
        if (event.target.id == "Sub") {

            var yemek = event.target.parentElement.parentElement.parentElement.children[1].innerText;
            var adet = event.target.parentElement.parentElement.parentElement.children[2].children[0].children[1].value;
            var siparişNo=event.target.parentElement.parentElement.parentElement.children[0].innerText;
            adet = parseInt(adet);
            
           
            if (adet != 0) {
                var order = '<tr id=><td>' + siparişNo + '</td><td>' + yemek + '</td><td>' + adet + '</td><td><button id="deleteFromBasket" class="btn btn-outline-warning">-</button</td></tr > ';
                document.getElementById("sepet").innerHTML += order;
            }
        }
        if (event.target.id == "subQuantity") {
           
            var quantity = parseInt(event.target.parentElement.children[1].value);
           
            if (quantity <2) { } else { quantity = quantity - 1; }
            event.target.parentElement.children[1].value = quantity;
            
        }
        if (event.target.id == "addQuantity") {
            var maxQuantity = parseInt(event.target.parentElement.children[1].className.split(" ")[1]);
            var quantity = parseInt(event.target.parentElement.children[1].value);
           
            if (quantity < maxQuantity) { quantity = quantity + 1; } else { }
            event.target.parentElement.children[1].value = quantity;

        }
        if (event.target.id == "deleteFromBasket") {
            event.target.parentElement.parentElement.remove();
        }
        if (event.target.id == "iptal") {

            var order = [];
            var table = document.getElementById("sepet");
            if (table.childElementCount > 0) {
                for (var i = 0; i < table.childElementCount; i++) {
                    var temp = { OrderId: parseInt(table.children[i].children[0].innerText), ProductName: table.children[i].children[1].innerText, Quantity: parseInt(table.children[i].children[2].innerText) };
                    order.push(temp);
                }
                while (table.firstChild) {
                    table.removeChild(table.lastChild);
                }
                $.ajax({
                    url: '/MenuView/UpdateOrder',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        order
                    },
                    statusCode: {
                        200: function () {
                            
                        }
                    }
                });
            }
            
        }
    });

</script>

ProjectRestaurant/ProjectRestaurant/Views/Restaurant/EditTable.cshtml
@model EditTableViewModel
@{
    ViewData["Title"] = "EditTable";
}
    <style>
        body {
            background-image: url('/image/cafebackground.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }
        .field-validation-error {
            padding: 3px;
            background-color: #b90000;
            color: white;
            border-radius:5px;
        }
        
        .form {
            background-color: rgba(0, 0, 0, 0.9);
            border-radius: 25px 25px 20px 25px;
            padding: 10px 10px 10px 0px;
        }

        .form p {
            color: rgb(255, 255, 255);
        }

        .form input {
            background-color: rgba(0, 0, 0, 0.50);
            border-color: rgb(255, 255, 255);
        }
        .form input[type=text] {
            background-color: rgba(0, 0, 0, 0.50);
            border-color: rgb(255, 255, 255);
            color:rgb(255, 255, 255);
        }

            .form input[type=text]:focus {
                background-color: rgba(0, 0, 0, 0.50);
                box-shadow:  3px 7px  rgba(255, 255, 255, 0.2);
                transition: 0.3s;
                color: aliceblue;
            }

        .form input[type=submit]:hover {
            background-color: rgba(2, 147, 0, 0.85);
            border-color: rgb(255, 255, 255);
        }
        .form a {
            background-color: rgba(0, 0, 0, 0.50);
            border-color: rgb(255, 255, 255);
        }
        .form a:hover {
            border-color: rgb(255, 255, 255);
        }
    </style>
    <div class="form">
        @using (Html.BeginForm(FormMethod.Post))
        {
            <div class="container ">
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="row">
                            <p class="col-md-4" style="margin-top:6px; vertical-align:central; text-align:center"><strong>Masa Adı :</strong></p>
                            @Html.TextBoxFor(x => x.TableName, null, new { @class = "col-md-6 form-control" })
                        </div>
                        <div>
                            @Html.HiddenFor(x => x.TableId)
                        </div>
                        <div style="text-align:center">
                            
                            @Html.ValidationMessageFor(x=>x.TableName)
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>


            </div>
            <div style="text-align:center;margin-top:20px;">
                <input class="btn btn-dark" type="submit" value="Kaydet" />
                <a class="btn btn-danger" asp-controller="Restaurant" asp-action="DeleteTable" asp-route-id="@Model.TableId">Sil</a>
            </div>
        }
    </div>

ProjectRestaurant/ProjectRestaurant/Views/Restaurant/Index.cshtml
@model List<TableViewModel>

@{
    ViewData["Title"] = "Index";
}

<style>
    body {
        background-image: url('/image/cafebackground.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
    #temp {
        padding:10px 10px 10px 0px;
        background-color: rgba(0, 0, 0, 0.7);
        border-radius:25px 25px 20px 25px;
    }
    #isAvaible-True {
        background-color: rgba(0, 0, 0, 0.50);
    }
        #isAvaible-True:hover {
            background-color: rgba(2, 147, 0, 0.85)
        }

        #isAvaible-True a {
            cursor: not-allowed;
            color: #ffffff;
            background-color: rgba(255, 255, 255, 0);
        }

    #isAvaible-False {
        background-color: rgba(0, 0, 0, 0.50);
        color: currentColor;
    }
        #isAvaible-False:hover {
            background-color: rgba(226, 0, 0, 0.85);
        }

        #isAvaible-False a {
            cursor: pointer;
            background-color: rgba(255, 255, 255, 0);
            color: #ffffff;
        }
    .oturmaIstegi {
        background-color: rgba(255, 255, 255, 0);
        color: #ffffff;
    }
    .col-md-4 {
        background-color: rgba(56, 56, 56, 0.55);
        border-radius: 25px 25px 25px 25px;
        
        
    }   
        #grid {
        display: grid;
        grid-template-columns: auto auto auto;
        padding: 10px;
        background-color: rgba(56, 56, 56, 0.55);
        border-radius: 25px 25px 25px 25px;
    }

    .card {
        padding: 5px;
        margin: 20px;
        box-shadow: 0 5px 10px 0 rgba(255, 255, 255, 0.1);
        transition: 0.3s;
        border-color: aliceblue;
    }

        .card:hover {
            box-shadow: 0 10px 20px 0 rgba(255, 255, 255, 0.7);
        }

        .card .card-header, .card-body {
            color: #ffffff;
        }

    .cardText {
        text-align: center;
    }

    #RequestList {
        max-height: 600px;
        overflow-y: scroll;
    }
</style>

<div class="container row" id="temp">
    <div class="col-md-8">

        <div class="container" id="grid">
            @foreach (var item in Model)
            {
                <div class="card" id="isAvaible-@item.IsAvailable">
                    <div class="card-header">
                        <h5 class="cardText">
                            @item.TableName
                        </h5>
                    </div>

                    <div class="card-body">
                        @if (item.IsAvailable)
                        {<p class="cardText">Müsait</p> }
                        else
                        {<p class=" cardText">Dolu</p>
                        }
                    </div>
                    @if (item.IsAvailable)
                    {
                        <div class="card-footer" id="@item.TableId"><div style="text-align:center"><a href="#" class="btn btn-light">Masa Detayı</a></div></div>
                    }
                    else
                    {
                        <div class="card-footer" id="@item.TableId"><div style="text-align:center"><a asp-action="TableDetail" asp-controller="Restaurant" asp-route-id="@item.TableId" target="_blank" class="btn btn-light">Masa Detayı</a></div></div>
                    }


                </div>
            }
        </div>
    </div>
    <div  class="col-md-4">
        <div style="margin-top:10px" id="RequestList">

        </div>
    </div>

</div>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/Istek.js"></script>

ProjectRestaurant/ProjectRestaurant/Views/Restaurant/TableDetail.cshtml
@model SessionViewModel
@{
    ViewData["Title"] = "MySession";
}
<style>
    body {
        background-image: url('/image/cafebackground.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
    .tableId {
        background-color: rgba(0, 0, 0, 0.8);
        border-radius: 25px 25px 20px 25px;
        padding: 10px 10px 10px 10px;
    }
    .tableId h2{
        color:white;
    }
    .card {
        background-color: rgba(0, 0, 0, 0.2);
        border: 1px solid rgba(0, 0, 0, 0.8);
        transition: 0.3s;
        border-color: white;
        color: white;
        
    }
        .card:hover {
            box-shadow: 0 5px 10px 0 white;
        }
    .card a{
        color:white;
        border-color:white;
    }
    .card a:hover{
        border-color:white;
        background-color:rgba(255, 106, 0, 1.00);
        
    }
    .restaurantMessage {
        width: 200px;
        word-wrap: break-word;
        margin-left: auto;
        margin-right: 5px;
        text-align: right;
        color: black;
        background-color: white;
        border-radius: 10px 10px 0px 10px;
        margin-top: 10px;
        padding: 0 5px 0 5px;
    }
    .customerMessage {
        width: 200px;
        word-wrap: break-word;
        text-align: left;
        margin-right: auto;
        margin-left: 5px;
        color: white;
        background-color: rgba(255, 106, 0, 1.00);
        border-radius: 10px 10px 10px 0px;
        margin-top: 10px ;
        padding:0 5px 0 5px;
    }
    #messageBox {
        height:300px;
        margin-top:10px; display:flex;
        flex-direction:column;
        overflow:auto;
    }
    .messageBoxContainer {
       background-color:rgba(0, 0, 0, 0.4);
       border-radius:10px 10px 10px 10px;
       border:1px solid white;
      
    }
    .messageTextBox {
        margin:5px 5px 15px 5px;
        height:30px;
        display:grid;
        grid-template-columns:80% 20%
    }
    #messageBut {
        font-size: 0.8rem;
    }
    #messageBut:hover{
        background-color:rgba(255, 106, 0, 1.00);
        color:white;
        
    }
    textarea {
        background-color: rgba(0, 0, 0, 0.2);
        color: white;
        border-radius:5px;
        border: 1px solid white;
        transition:0.3s;
    }
        textarea:focus {
            background-color: rgba(0, 0, 0, 0.7);
            color: white;
            border-radius: 5px;
            border-color: white;
            border :1px solid white ;
            outline:none;
            box-shadow:0 0 4px white;
            
        }
</style>
<div class="container tableId" id="TableDetail">
    <div><h2>@Model.TableName</h2></div>
    <div class="row">
        <div class="col-md-8">
            <table class="table table-dark table-striped table-hover">
                <thead>
                    <tr>
                        <th>Ürün</th>
                        <th>Adet</th>
                        <th>Fiyat</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Order.Count; i++)
                    {
                        if (Model.Order[i].isDelivered)
                        {
                            <tr>
                                <td>@Model.Order[i].ProductName</td>
                                <td>@Model.Order[i].Quantity</td>
                                <td>@Model.Order[i].Price</td>

                            </tr>
                        }
                        else
                        { 
                            <tr class="table-secondary" style="color:#000000">
                                <td>@Model.Order[i].ProductName</td>
                                <td>@Model.Order[i].Quantity</td>
                                <td>@Model.Order[i].Price</td>
                            </tr>
                        }

                    }

                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <div id="sessionId" style="text-align:center">Müşteri No:@Model.SessionId</div>
                </div>
                <div class="card-body">
                    <div>
                        <div><p style="text-align:center">Masa :@Model.TableName</p></div>
                        <div><p style="text-align:center">Başlangıç: @Model.StartDate</p></div>
                        <div><p style="text-align:center">Toplam Fiyat:@Model.TotalFee</p> </div>
                        <div style="text-align:center; display:grid; grid-template-columns:33% 33% 33%" >

                            <a asp-action="DeliverOrder" asp-controller="Restaurant" asp-route-id="@Model.SessionId" class="btn btn-outline-dark float-left">Sipariş Hazır</a>
                            <div  id="@Model.TableId"><a asp-action="CloseSession" asp-controller="Restaurant" asp-route-id="@Model.SessionId" id="closeSession" class="btn btn-outline-dark">Hesabı Kapat</a></div>
                            <div id="@Model.TableId"><a target="_blank" asp-action="CancelOrders" asp-controller="Restaurant" asp-route-id="@Model.TableId"  class="btn btn-outline-dark">Sipariş İptalleri</a></div>
                        </div>
                        

                    </div>
                </div>
                <div>

                </div>
            </div>
            <div class="messageBoxContainer">
                <div id="messageBox">
                    
                </div>
                <div class="messageTextBox">
                    <textarea placeholder="Mesajınız..." id="messageText" style="height:auto; resize:none"></textarea>
                    <button id="messageBut"  class="btn btn-outline-light">Gönder</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/Istek.js"></script>
<script>
    $(document).ready(function () {
        getMessages();
    });
    $("#messageBut").click(function () {
        $.ajax({
            type: "post",
            url: "/MenuView/PostMessage",
            data: {
                SessionId: $("#sessionId").text().split(":")[1],
                From: "Restoran",
                To: $("#sessionId").text().split(":")[1],
                MessageText: $("#messageText").val()
            },
            success: function (result) {
                getMessages();
            }

        })
    })
    function getMessages() {
        $.ajax({
            type: "get",
            url: "/MenuView/GetMessages",
            dataType:"json",
            data: {
                sessionId: $("#sessionId").text().split(":")[1]
            },
            success: function (result) {
                $("#messageBox div").html('');
                $('#messageText').val("");
                
                for (var i = 0; i < result.length; i++) {
                    
                    if (result[i].from == "Restoran")
                    {
                        
                        var temp = "<div class=restaurantMessage > <p>" + result[i].messageText + "</p></div >";
                        
                    }
                    else {
                        var temp = "<div class=customerMessage > <p>" + result[i].messageText + "</p></div >"; 
                        
                    }
                    $("#messageBox").append(temp);
                    $('#messageBox').scrollTop($('#messageBox').prop('scrollHeight'));
                }
            },
            error: function (result) {
                console.log(result);
            
}
        })
    }
</script>

ProjectRestaurant/ProjectRestaurant/Views/Restaurant/Tables.cshtml
@model List<TableViewModel>

@{
    ViewData["Title"] = "Tables";
}
<style>
    body {
        background-image: url('/image/cafebackground.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
    #grid {
        display: grid;
        grid-template-columns: auto auto auto;
        padding: 10px;
        background-color: rgba(56, 56, 56, 0.55);
        border-radius: 25px 25px 25px 25px;
    }

    .card {
        background-color: rgba(0, 0, 0, 0.70);
        padding: 5px;
        margin: 20px;
        box-shadow: 0 5px 10px 0 rgba(255, 255, 255, 0.1);        
        transition: 0.3s;
        color: #ffffff;
        border-color:aliceblue;
    }
        .card:hover {
            background-color: rgba(225, 138, 0, 0.95);
            box-shadow: 0 10px 20px 0 rgba(255, 255, 255, 0.2);
        }

        .card a:hover {
            background-color: rgba(255, 255, 255, 0);
            color: #ffffff;
        }

    .card, .card-header, .card-body {
    }

    .cardText {
        text-align: center;
    }
    #newTable {
        background-color: rgba(0, 0, 0, 0.0)
    }
        #newTable:hover {
            background-color: rgba(225, 138, 0, 0.85);
            color: #ffffff;
        }
</style>

<div >
    <a id="newTable" class="btn btn-outline-light float-left" asp-action="NewTable" asp-controller="Restaurant">Yeni Masa</a>
    
</div>
<div class="container " id="grid">
    @foreach (var item in Model)
    {@Html.HiddenFor(x => item.TableId)
    <div class="card" id="isAvaible-@item.IsAvailable">
        <div class="card-header">
            <h5 class="cardText">
                @item.TableName
            </h5>
        </div>

        <div class="card-footer" id="@item.TableId">
            <div style="text-align:center">
                <a class=" btn btn-outline-light" asp-action="EditTable" asp-controller="Restaurant" asp-route-id="@item.TableId">Düzenle</a>
            </div>
        </div>
    </div>
}
</div>