ProjectRestaurant/ProjectRestaurant/Controllers/MenuViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.Messaging;
using Newtonsoft.Json;
using ProjectRestaurant.Data.Context;
using ProjectRestaurant.Data.Entities;
using ProjectRestaurant.Models;
using ProjectRestaurant.Service.Dto;
using ProjectRestaurant.Service.Service;

namespace ProjectRestaurant.Controllers
{
    public class MenuViewController : Controller
    {
         
        private readonly MenuService _service;
        private readonly RestaurantDbContext _context;
        private readonly IMapper _mapper;
        public MenuViewController(MenuService service, RestaurantDbContext context, IMapper mapper)
        {
            _mapper = mapper;
            _service = service;
            _context = context;
        }

        public IActionResult Index()
        {
            if (Request.Cookies["SessionId"]== null){
                return RedirectToAction("Tables", "Home");
            }
            var sessionId =int.Parse( Request.Cookies["SessionId"]);
            var result= _service.CheckIfTableIsAvaibleBySessionId(sessionId);

            if (result == true)
            {
                Response.Cookies.Delete("SessionId");
                return RedirectToAction("Tables", "Home");
                //Eğer müşteri sayfasını kapattıktan sonra Restoran hesabı kapatmışsa, müşteri bağlandığında bunun kontrolü yapılır
            }

            var productTypes = _service.GetProductTypes();
            var mapped = _mapper.Map<List<ProductTypeViewModel>>(productTypes);
            var table = _service.GetTableBySessionId(int.Parse(Request.Cookies["SessionId"]));
            TempData["SessionId"] = Request.Cookies["SessionId"];
            ViewBag.tableId = table.TableId;
            ViewBag.tableName = table.TableName;

            return View(mapped);
        }
        public IActionResult GetProduct(int id)
        {
            var product = _service.GetProductTypeById(id);
            var mapped = _mapper.Map<List<MenuViewModel>>(product);

            return View(mapped);
        }
        public async Task< IActionResult> Order(List<OrderViewModel> order)
        {
            if (Request.Cookies["SessionId"]==null)
            {
                return RedirectToAction(nameof(Index));
            }
            int session = int.Parse( Request.Cookies["SessionId"]);
            var mapped = _mapper.Map<List<OrderDto>>(order);
            await _service.MakeOrder(mapped, session);
            return Ok();
        }
        public  IActionResult MySession()
        {
            if (Request.Cookies["SessionId"]==null)
            {
                return RedirectToAction(nameof(Index));
            }
            int session =int.Parse( Request.Cookies["SessionId"]);
            var ses=_service.MySession(session);
            var mapped = _mapper.Map<SessionViewModel>(ses);
            return View(mapped);
        }
        public IActionResult CloseSession()
        {
            
            Response.Cookies.Delete("SessionId");
            return RedirectToAction("Tables","Home");
        }
        [HttpGet]
        public JsonResult GetMessages(int sessionId)
        {
            var messages = _service.GetMessages(sessionId);

            return Json(messages);

        }
        public  async Task<IActionResult> PostMessage(MessageJson message)
        {
            var mapped = _mapper.Map<Data.Entities.Message>(message);
            await _service.PostMessages(mapped);
            return Ok();
        }
        public IActionResult UpdateOrder(List<OrderUpdateModel> order)
        {

            List < OrderUpdateDto> orderList = new List<OrderUpdateDto>();
            foreach (var item in order)
            {
                orderList.Add(
                    new OrderUpdateDto { 
                        OrderId=item.OrderId,
                        ProductName=item.ProductName,
                        Quantity=(float) item.Quantity
                    }
                    );
            }
             _service.OrderUpdate(orderList); 
            return Ok();
        }
    }
}

ProjectRestaurant/ProjectRestaurant/Views/MenuView/GetProduct.cshtml
@model List<MenuViewModel>
@{
    ViewData["Title"] = "GetProduct";
}

<h1>Menü İçerik</h1>

<div class="container">
    <div class="row">
        <div class="col-md-2"><strong>Ürün Adı</strong></div>
        <div class="col-md-2"><strong>Ürün Fİyatı</strong></div>
        <div class="col-md-2"><strong>Ürün Miktarı</strong></div>
        <div class="col-md-2"><strong>Ürün Açıklaması</strong></div>
        <div class="col-md-2"><strong>Ürün Türü</strong></div>
    </div>
</div>


@foreach (var menu in Model)
{
    <div class="container">
        <div class="row">
            <div class="col-md-2">@menu.ProductName</div>
            <div class="col-md-2">@menu.Price</div>
            <div class="col-md-2">@menu.Quantity</div>
            <div class="col-md-2">@menu.Description</div>
            <div class="col-md-2">@menu.ProductType.Type</div>
        </div>
    </div>
}

ProjectRestaurant/ProjectRestaurant/Views/MenuView/Index.cshtml
@model List<ProductTypeViewModel>

<style>
    body {
        background-image: url('image/cafeBackground.jpg ');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }

    .col-md-4 a {
        background-color: rgba(2, 147, 0, 0);
        color: rgb(255, 255, 255);
        border-color: rgb(255, 255, 255);
    }

    .col-md-4 button {
        background-color: rgba(2, 147, 0, 0);
        color: rgb(255, 255, 255);
        border-color: rgb(255, 255, 255);
    }

    .more {
        display: none
    }

    .col-md-4 a:hover {
        background-color: #ee7500;
        border-color: rgb(255, 255, 255);
    }

    .col-md-4 button:hover {
        background-color: #ee7500;
        border-color: rgb(255, 255, 255);
    }

    #grid {
        display: grid;
        grid-template-columns: 20% 20% 20% 20% 20%;
        padding-left: 10px;
        padding-right: 10px;
    }

        #grid div {
            text-align: center;
            vertical-align: middle;
            padding-bottom: 25px;
            padding-top: 25px;
            margin-top: auto;
            margin-bottom: auto;
        }

        #grid .row {
            margin-left: auto;
            margin-right: auto;
        }

    #quantityBox {
        resize: none;
        width: 50px;
        height: 40px;
        white-space: normal;
        text-align: justify;
        -moz-text-align-last: center;
        text-align-last: center;
    }

    .tableId {
        background-color: rgba(0, 0, 0, 0.8);
        border-radius: 25px 25px 20px 25px;
        padding: 10px 10px 10px 10px;
    }
    .modal-content {
        background-color: rgba(0, 0, 0, 1);
        color: white;
        text-align:center;  
    }
    #modalTitle {
        margin: auto;
        font-style: italic;
        color: white;
        font-size: 30px;
    }
    
</style>
<div class="container tableId " id="@ViewBag.tableId*@ViewBag.tableName">

    <div class="row">

        <div class="col-md-8">
            @for (int i = 0; i < Model.Count; i++)
            {<div class="card">
                    @if (Model[i].Menu.Count > 0)
                    {
                        <div class="panel bg-light panel-default">
                            <div class="panel-heading">
                                <h4 class="card-header" style="text-align:center">
                                    <a style="color:#000000" data-toggle="collapse" href="@("#collapse"+i)">@Model[i].Type</a>
                                </h4>
                            </div>
                            <div id="@("collapse"+i)" class="panel-collapse collapse">
                                @for (int k = 0; k < Model[i].Menu.Count; k++)
                                {
                                    <div class="row " id="grid">
                                        <div class="menu-text">@Model[i].Menu[k].ProductName</div>
                                        <div>
                                            <span data-toggle="modal" data-target="#myModal" class="less">
                                                @if (Model[i].Menu[k].Description.Length < 11)
                                                {
                                                    @Model[i].Menu[k].Description
                                                }
                                                else
                                                {
                                                    @Model[i].Menu[k].Description.Substring(0, 10)
                                                }



                                            </span><span class="dots">...</span>
                                            <span class="more">@Model[i].Menu[k].Description</span>
                                        </div>
                                        <div>@Model[i].Menu[k].Price ₺</div>
                                        <div class="row">
                                            <button id="subQuantity" class="btn btn-outline-danger">-</button>
                                            <textarea disabled="disabled" id="quantityBox" class="form-control" rows="1" maxlength="2">1</textarea>
                                            <button id="addQuantity" class="btn btn-outline-success">+</button>
                                        </div>
                                        <div><button id="Add" class="btn btn-outline-primary">+</button></div>
                                    </div>
                                }
                            </div>
                        </div>
                    }
                </div>
            }

        </div>
        <div class="col-md-4">
            <table class="table table-dark table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col">Ürün</th>
                        <th scope="col">Fiyat</th>
                        <th scope="col">Adet</th>
                        <th scope="col">Toplam</th>
                        <th scope="col">Çıkar</th>
                    </tr>
                </thead>
                <tbody id="sepet">
                </tbody>
            </table>
            <div style="text-align:center">
                <button id="makeOrder" class="btn btn-outline-dark">Sipariş Ver</button>
                <a class="btn btn-outline-dark" asp-controller="MenuView" asp-action="MySession">Hesabım</a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 id="modalTitle" class="modal-title">Detay</h1>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span style="color:white;" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/Istek.js"></script>
<script type="text/javascript">


    document.body.addEventListener("click", function (event) {
        if (event.target.id == "Add") {
            var yemek = event.target.parentElement.parentElement.children[0].innerText;
            var fiyat = event.target.parentElement.parentElement.children[2].innerText.split(" ")[0];
            var adet = event.target.parentElement.parentElement.children[3].children[1].value;
            adet = parseInt(adet);
            fiyat = parseInt(fiyat);
            var toplam = fiyat * adet;
            if (adet != 0) {
                var order = '<tr id=><td>' + yemek + '</td><td>' + fiyat + '₺</td><td>' + adet + '</td><td>' + toplam + '₺</td><td><button id="deleteFromBasket" class="btn btn-outline-warning">-</button</td></tr > ';
                document.getElementById("sepet").innerHTML += order;
            }
        }
        if (event.target.id == "subQuantity") {
            var quantity = parseInt(event.target.parentElement.children[1].value);

            if (quantity == 0) { } else { quantity = quantity - 1; }
            event.target.parentElement.children[1].value = quantity;
        }
        if (event.target.id == "addQuantity") {
            var quantity = parseInt(event.target.parentElement.children[1].value);
            if (quantity < 99) { quantity = quantity + 1; } else { }
            event.target.parentElement.children[1].value = quantity;
        }
        if (event.target.id == "deleteFromBasket") {
            event.target.parentElement.parentElement.remove();
        }
        if (event.target.id == "makeOrder") {

            var order = [];
            var table = document.getElementById("sepet");
            if (table.childElementCount > 0) {
                for (var i = 0; i < table.childElementCount; i++) {
                    var temp = { ProductName: table.children[i].children[0].innerText, Price: parseInt(table.children[i].children[1].innerText), Quantity: parseInt(table.children[i].children[2].innerText) };
                    order.push(temp);
                }
                while (table.firstChild) {
                    table.removeChild(table.lastChild);
                }
                $.ajax({
                    url: '/MenuView/Order',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        order
                    },
                    statusCode: {
                        200: function () {
                            alert("Siparişiniz Başarıyla İletildi");
                        }
                    }
                });
            }
            else { alert("Sepetiniz Boş") }
        }
        if (event.target.className == "less") {


            document.getElementsByClassName("modal-body")[0].innerHTML = event.target.parentElement.children[2].innerHTML;
            document.getElementsByClassName("modal-title")[0].innerHTML = event.target.parentElement.parentElement.children[0].innerHTML;

        } 
    });

</script>










@*


    @foreach (var menu in Model)
    {
        <div class="row">


            <div class="col-md-2">
                @Html.ActionLink(menu.Type, "GetProduct", new { id = menu.ProductTypeId }, new { @class = "btn btn-outline-primary" })<br /><br />
            </div>
        </div>

    }


*@

ProjectRestaurant/ProjectRestaurant/Views/MenuView/MySession.cshtml
@model SessionViewModel
@{
    ViewData["Title"] = "MySession";
}
<style>
    body {
        background-image: url('/image/cafebackground.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }

    .card {
        background-color: rgba(0, 0, 0, 0.2);
        border: 1px solid rgba(0, 0, 0, 0.8);
        transition: 0.3s;
        border-color: white;
        color: white;
    }

        .card:hover {
            box-shadow: 0 5px 10px 0 white;
        }

    .tableId {
        background-color: rgba(0, 0, 0, 0.8);
        border-radius: 25px 25px 20px 25px;
        padding: 10px 10px 10px 10px;
    }

        .tableId h2 {
            color: rgb(255, 255, 255);
        }

        .tableId a {
            background-color: rgba(0, 0, 0, 0);
            color: rgb(255, 255, 255);
            border-color: rgb(255, 255, 255);
        }

            .tableId a:hover {
                background-color: #ee7500;
                color: rgb(255, 255, 255);
                border-color: rgb(255, 255, 255);
            }

    .card button {
        color: white;
        border-color: white;
    }

        .card button:hover {
            border-color: white;
            background-color: rgba(255, 106, 0, 1.00);
        }

    .restaurantMessage {
        width: 200px;
        word-wrap: break-word;
        margin-right: auto;
        margin-left: 5px;
        text-align: left;
        color: black;
        background-color: white;
        border-radius: 10px 10px 10px 0px;
        margin-top: 10px;
        padding:0 5px 0 5px;
    }

    .customerMessage {
        width: 200px;
        word-wrap: break-word;
        text-align: left;
        margin-left: auto;
        margin-right: 5px;
        text-align: right;
        color: white;
        background-color: rgba(255, 106, 0, 1.00);
        border-radius: 10px 10px 0px 10px;
        margin-top: 10px;
        padding: 0 5px 0 5px;
    }

    #messageBox {
        height: 300px;
        margin-top: 10px;
        display: flex;
        flex-direction: column;
        overflow: auto;
    }

    .messageBoxContainer {
        background-color: rgba(0, 0, 0, 0.4);
        border-radius: 10px 10px 10px 10px;
        border: 1px solid white;
    }

    .messageTextBox {
        margin: 5px 5px 15px 5px;
        height: 30px;
        display: grid;
        grid-template-columns: 80% 20%
    }

    #messageBut {
        font-size: 0.8rem;
    }

        #messageBut:hover {
            background-color: rgba(255, 106, 0, 1.00);
            color: white;
        }

    textarea {
        background-color: rgba(0, 0, 0, 0.2);
        color: white;
        border-radius: 5px;
        border: 1px solid white;
        transition: 0.3s;
    }

        textarea:focus {
            background-color: rgba(0, 0, 0, 0.7);
            color: white;
            border-radius: 5px;
            border-color: white;
            border: 1px solid white;
            outline: none;
            box-shadow: 0 0 4px white;
        }
</style>
<div class="container tableId" id="@Model.TableId*@Model.TableName">
    <div style="display:flex; justify-content:space-between"><h2>@Model.TableName</h2><a class=" btn btn-outline-dark" asp-controller="MenuView" asp-action="Index">Menü</a></div>
    <div class="row" style="margin-top:20px">
        <div class="col-md-8">
            <table class="table table-dark table-striped table-hover">
                <thead>
                    <tr>
                        <th>Ürün</th>
                        <th>Adet</th>
                        <th>Fiyat</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Order.Count; i++)
                    {
                        <tr>
                            <td>@Model.Order[i].ProductName</td>
                            <td>@Model.Order[i].Quantity</td>
                            <td>@Model.Order[i].Price</td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <div id="sessionId" style="text-align:center">Müşteri No: @Model.SessionId</div>
                </div>
                <div class="card-body">
                    <div>
                        <div><p style="text-align:center">Masa :@Model.TableName</p></div>
                        <div><p style="text-align:center">Başlangıç: @Model.StartDate</p></div>
                        <div><p style="text-align:center">Toplam Fiyat:@Model.TotalFee</p> </div>
                        <div style="text-align:center"><button id="checkoutReq" class="btn btn-outline-dark">Hesap İste</button></div>
                    </div>
                </div>
                <div>

                </div>
            </div>
            <div class="messageBoxContainer">
                <div id="messageBox">

                </div>
                <div class="messageTextBox">
                    <textarea placeholder="Mesajınız..." id="messageText" style="height:auto; resize:none"></textarea>
                    <button id="messageBut" class="btn btn-outline-light">Gönder</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/Istek.js"></script>


<script>
    $(document).ready(function () {
        getMessages();
        
    });
    $("#messageBut").click(function () {
        $.ajax({
            type: "post",
            url: "/MenuView/PostMessage",
            data: {
                SessionId: $("#sessionId").text().split(":")[1],
                From: $("#sessionId").text().split(":")[1],
                To: "Restoran",
                MessageText: $("#messageText").val()
            },
            success: function (result) {
                getMessages();
            }

        })
    })
    function getMessages() {
        $.ajax({
            type: "get",
            url: "/MenuView/GetMessages",
            dataType: "json",
            data: {
                sessionId: $("#sessionId").text().split(":")[1]
            },
            success: function (result) {
                $("#messageBox div").html('');
                $('#messageText').val("");

                for (var i = 0; i < result.length; i++) {

                    if (result[i].from == "Restoran") {

                        var temp = "<div class=restaurantMessage > <p>" + result[i].messageText + "</p></div >";

                    }
                    else {
                        var temp = "<div class=customerMessage > <p>" + result[i].messageText + "</p></div >";

                    }
                    $("#messageBox").append(temp);
                    $('#messageBox').scrollTop($('#messageBox').prop('scrollHeight'));
                }
            },
            error: function (result) {
                console.log(result);

            }
        })
    }
</script>